Eindhoven Musuem scanner (alternative, using RC522 RFID scanner)
                                              
This code only imitates wokring scanner. It can read the token, 
but it cannot write to it or send data to the Processing app.
                                         
It was made for demo purposes and because we didn't got PN532 on time.

Some parts of code is taken from example codes made by GARGANTUA from RoboCreators.com & paradoxalabs.com
